### ISSUE TITLE
Reason： App Installer failed to install package dependencies. Ask the developer for package.

### ISSUE THREAD

**Issue by lhj5426** [poochie89/SnipDo-Extensions#10]
![image](https://user-images.githubusercontent.com/30548000/186654590-e75b4783-a4f6-40d3-a728-cb0ec2364eb4.png)
Have you considered developing an .exe?
win APP is a piece of shit

**Comment by poochie89** [comment]
Hey, I rely on some desktop bridge features so that wont be possible.
I modified the appinstaller file, could you try to download it again?

**Comment by lhj5426** [comment]
![image](https://user-images.githubusercontent.com/30548000/186746713-6d4f64c8-d940-42d8-b0f6-73d8a7174b4a.png)
Redownloaded the same

win app shit

Is there an .exe
![image](https://user-images.githubusercontent.com/30548000/186746956-5bed08af-a2c6-4c8f-9c2f-0eb03aa3110a.png)

**Comment by poochie89** [comment]
Could you contact me per email so i could try a bunch of different deployment techniques
