### ISSUE TITLE
doubts about resources

### ISSUE THREAD

**Issue by cleuton4k** [poochie89/SnipDo-Extensions#101]
What are these resources for?
![654](https://github.com/poochie89/SnipDo-Extensions/assets/90144967/ed116b2f-5d4d-423a-8701-8c9b9638952b)
![655](https://github.com/poochie89/SnipDo-Extensions/assets/90144967/7c86be13-76e4-4599-b9e1-e43308a3af8f)

**Comment by poochie89** [comment]
Hide on ctrl+c hides the bar when it is showing and ctrl+c is pressed
the other one shows the paste bar when the paste extension in the textextension bar is rigthclicked
