### ISSUE TITLE
being able to modify the time for opening insertions

### ISSUE THREAD

**Issue by cleuton4k** [poochie89/SnipDo-Extensions#102]
I would like you to add an option to choose how long to hold the left mouse click to open the insertion actions.

![656](https://github.com/poochie89/SnipDo-Extensions/assets/90144967/600dc03e-07a4-4050-aed5-d0e44dbd2fa3)
![15939163-controle-deslizante-com-modelo-de-elemento-de-interface-do-usuario-de-indicadores-componente-de-painel-de-isolado-editavel-interface-de-usuario-plana-apresentacao-de-dados-visuais-widget-de-web-design-para-aplicativo-m](https://github.com/poochie89/SnipDo-Extensions/assets/90144967/b3c0f9de-2582-4acf-bec0-29cfd6281015)

**Comment by poochie89** [comment]
will add that
