### ISSUE TITLE
version shown in snipdo is different from the store

### ISSUE THREAD

**Issue by cleuton4k** [poochie89/SnipDo-Extensions#107]
![662](https://github.com/poochie89/SnipDo-Extensions/assets/90144967/fc534ae6-699d-4c89-b062-e058f73f45f0)
![661](https://github.com/poochie89/SnipDo-Extensions/assets/90144967/2c1e8121-1a3a-4929-8d46-59b28bd717ef)

**Comment by poochie89** [comment]
The store one is the correct version, just forgot to update the source code file
