### ISSUE TITLE
[Feature Request] Always start as administrator

### ISSUE THREAD

**Issue by rp1231** [poochie89/SnipDo-Extensions#11]
Snip Do doesn't work in apps with administrator privileges.
It would be nice to have an option to Always start as administrator, so that it can work in apps with admin rights.
For eg. If you're using notepad++ with admin rights

**Comment by poochie89** [comment]
Great idea.
 Will ad this if possible

**Comment by poochie89** [comment]
They finally approved this, should be out in the next couple of days
