### ISSUE TITLE
(bug) text prompts are shifted to the right.

### ISSUE THREAD

**Issue by cleuton4k** [poochie89/SnipDo-Extensions#113]
![690](https://github.com/poochie89/SnipDo-Extensions/assets/90144967/bc48d7ca-a4f3-4c82-912f-5a566c406b16)

**Comment by poochie89** [comment]
Don’t understand

**Comment by cleuton4k** [comment]
![final](https://github.com/poochie89/SnipDo-Extensions/assets/90144967/bfce8266-1d1e-41d4-8eb4-d8db1414f042)

**Comment by poochie89** [comment]
ah ok: )
