### ISSUE TITLE
add support for extension updates.

### ISSUE THREAD

**Issue by cleuton4k** [poochie89/SnipDo-Extensions#114]
I noticed that a user has version 2 of the currency converter, while my version is version 3.
- how does the current extension upgrade system work?
- would it be possible to add an automatic update system?
![676](https://github.com/poochie89/SnipDo-Extensions/assets/90144967/a70fcec6-0c4d-44e3-8cd3-904bd0803b11)
![677](https://github.com/poochie89/SnipDo-Extensions/assets/90144967/2cf47183-03f0-4620-9ea4-4ab1081180bc)

**Comment by poochie89** [comment]
Currently one has to manually update
This is quite a task with my current system so its not a priority
