### ISSUE TITLE
Post/Patch request

### ISSUE THREAD

**Issue by bukit-kronik** [poochie89/SnipDo-Extensions#116]
I want to highlight a text then send http post/patch, how can I do this with powershell/python code?

This is a very useful extension to be added to SnipDo, I'm a long time pro user and would be grateful to have this in my workflow.

Thanks

**Comment by poochie89** [comment]
Easiest to use powershellChatgpt can help Am 27.02.2024 um 23:38 schrieb Bukit Sorrento ***@***.***>:﻿
I want to highlight a text then send http post/patch, how can I do this with powershell/python code?
This is a very useful extension to be added to SnipDo, I'm a long time pro user and would be grateful to have this in my workflow.
Thanks

**Comment by bukit-kronik** [comment]
I've tried it, but didn't get response back, I need an example, more detailed tutorial or a cookbook with files.

**Comment by bukit-kronik** [comment]
Please consider develop http request extension for nocode/non technical users. Thank you.
