### ISSUE TITLE
White screen on pop-up window

### ISSUE THREAD

**Issue by arthackrc** [poochie89/SnipDo-Extensions#12]
I'm using the pro version and dark theme on windows. The pop-up window style doesn't go well. The button is still there, but I need to guess where it's actually there.

![image](https://user-images.githubusercontent.com/45164273/194335480-0dd28c8f-15d2-4388-9d17-264b4a0ace91.png)

**Comment by poochie89** [comment]
Thanks for the bug report,
could you send me your windows color accent and OS dark/light mode settings? Also your Windows Version.

**Comment by arthackrc** [comment]
SnipDo version 3.0.17.0
![image](https://user-images.githubusercontent.com/45164273/194460675-5486a620-2046-46dd-81ce-b7b8a2185f20.png)

SnipDo Appearance Settings :
![image](https://user-images.githubusercontent.com/45164273/194461170-be67d206-6050-4eef-85e1-5bd2e98fe556.png)

and here's my backup setting from SnipDo :
[settings.zip](https://github.com/poochie89/SnipDo-Extensions/files/9730455/settings.zip)

Windows 11 version 22H2 OS Build 22621.608
![image](https://user-images.githubusercontent.com/45164273/194460973-16b21d77-fa87-4863-b716-984fa60bd2ec.png)

Windows theme :
![image](https://user-images.githubusercontent.com/45164273/194460826-bc4ea8e2-3592-4dae-85dc-ba5ccccbe9fe.png)

**Comment by poochie89** [comment]
Thanks, can reproduce and found bug
