### ISSUE TITLE
Always copy when selecting text is not working

### ISSUE THREAD

**Issue by cleuton4k** [poochie89/SnipDo-Extensions#17]
If I understand correctly when the function "Always copy when selecting text" is activated, the selected text should be automatically copied to the clipboard, but it is not working.
![9](https://user-images.githubusercontent.com/90144967/203883123-c5d13b87-b9b6-4b58-a4ec-4335efe6ff68.png)

**Comment by poochie89** [comment]
Found the problem, fix coming in next update
