### ISSUE TITLE
the extension to open the text in the editor does not work for my editor.

### ISSUE THREAD

**Issue by cleuton4k** [poochie89/SnipDo-Extensions#18]
https://apps.microsoft.com/store/detail/notepads-app/9NHL4NSC67WM?hl=pt-br&gl=br

https://user-images.githubusercontent.com/90144967/203883979-fa0ea0eb-4a8f-4869-a0b4-ae5838460f34.mp4

**Comment by poochie89** [comment]
To achieve this, you will eather have to:
- write your own extension
- or associate .txt files with your app

**Comment by cleuton4k** [comment]
could you create a script for notepads?
