### ISSUE TITLE
APP does not work properly on certain website

### ISSUE THREAD

**Issue by cleuton4k** [poochie89/SnipDo-Extensions#22]
https://thehackernews.com/2022/12/hackers-leak-another-set-of-medibank.html

https://user-images.githubusercontent.com/90144967/205084774-d7348af3-10e8-46be-8197-e005e3301cc7.mp4

**Comment by poochie89** [comment]
Hey unfortunately this is the fault of the website and is not fixable by meAm 01.12.2022 um 15:55 schrieb cleuton4k ***@***.***>:﻿
https://thehackernews.com/2022/12/hackers-leak-another-set-of-medibank.html
https://user-images.githubusercontent.com/90144967/205084774-d7348af3-10e8-46be-8197-e005e3301cc7.mp4

**Comment by cleuton4k** [comment]
ok
