### ISSUE TITLE
small bug in translation

### ISSUE THREAD

**Issue by cleuton4k** [poochie89/SnipDo-Extensions#23]
![41](https://user-images.githubusercontent.com/90144967/205087676-df40aaf2-105a-43c0-9592-8d408cb2d583.png)
![42](https://user-images.githubusercontent.com/90144967/205087680-da5cb699-97ec-43b1-8ed5-175061129a42.png)

**Comment by poochie89** [comment]
Got it, fix coming

**Comment by poochie89** [comment]
Fixed
