### ISSUE TITLE
Entries are duplicated on the clipboard

### ISSUE THREAD

**Issue by cleuton4k** [poochie89/SnipDo-Extensions#25]
https://user-images.githubusercontent.com/90144967/207119167-eb8f5e36-37b1-4362-afc1-853b1d0b2222.mp4

**Comment by poochie89** [comment]
This is intended behavior.
To paste something it must be copied on clipboard. There is no way to delete it

**Comment by cleuton4k** [comment]
But why doesn't that happen using the Windows clipboard?

https://user-images.githubusercontent.com/90144967/207132395-bc99206c-a274-49ec-a6a1-324abe3e177c.mp4

**Comment by poochie89** [comment]
Since they manage the clipboard, they can simply ignore the paste process. The developers dont have that access
