### ISSUE TITLE
improvements to the clipboard

### ISSUE THREAD

**Issue by cleuton4k** [poochie89/SnipDo-Extensions#26]
* add more entries to artboard history as the current limit is 10 entries.
* add option to remove individual entries and all clipboard.
* make the snipdo clipboard independent of the windows clipboard, thus removing some limitations.

https://user-images.githubusercontent.com/90144967/207125373-25306789-be78-4163-87e8-ffe9b5148600.mp4

https://user-images.githubusercontent.com/90144967/207158578-4b1a9e8b-a35f-4513-a974-096c5e8a537b.mp4

**Comment by poochie89** [comment]
thx for the suggestions, will take these into consideration
