### ISSUE TITLE
window action buttons are duplicated

### ISSUE THREAD

**Issue by cleuton4k** [poochie89/SnipDo-Extensions#29]
![98](https://user-images.githubusercontent.com/90144967/210141277-7930d567-cfe5-445c-a5cb-89ad44aa273f.png)

**Comment by poochie89** [comment]
Which os version are you on?

**Comment by cleuton4k** [comment]
Edition	         Windows 10 Pro
Version	         22H2
OS build	        19045.2364
Experience	Windows Feature Experience Pack 120.2212.4190.0

**Comment by poochie89** [comment]
isis fixed in 3.0.31?

**Comment by cleuton4k** [comment]
no, it remains the same.
