### ISSUE TITLE
add a button to paste and go

### ISSUE THREAD

**Issue by cleuton4k** [poochie89/SnipDo-Extensions#31]
I would like you to add a button to paste and go, just like "paste and go" in the browser. in which when clicking on the button it pastes and simulates pressing the enter button on the keyboard.
![120](https://user-images.githubusercontent.com/90144967/211411047-9b115fe0-3032-4b24-b3b0-103d3d6de845.png)
![paste-and-go-chrome](https://user-images.githubusercontent.com/90144967/211411055-007472d3-d8c4-4afc-aef0-8f30e0d1716c.png)

**Comment by poochie89** [comment]
This extension is now available in the paste extension store

**Comment by cleuton4k** [comment]
I have an APP called LOGITECH OPTIONS PLUS and it notifies me when I press some keys like caps lock and num lock, but when I use the paste and go extension the app informs me as if I had pressed the num lock key, you would know me say why?

https://user-images.githubusercontent.com/90144967/211585440-77ba68f6-3709-45b0-bb30-f73757aa38d2.mp4
