### ISSUE TITLE
prevent the clipboard from exceeding the screen area. (bug)

### ISSUE THREAD

**Issue by cleuton4k** [poochie89/SnipDo-Extensions#33]

**Comment by poochie89** [comment]
What is your monitor setup? How many extension/folders you got? Can not reproduce this…

**Comment by cleuton4k** [comment]
1. The problem with the taskbar exceeding the screen was being caused by the "show text for copy, cut and paste" feature, and I already solved this by disabling this feature.
2. The problem remains is the clipboard.

https://user-images.githubusercontent.com/90144967/225109902-7edfc7f9-2b4f-4952-90ce-38998ac3a637.mp4

**Comment by cleuton4k** [comment]
please make the clipboard closer to the icon. when clicking at the bottom of the screen, the clipboard is centered.
![before](https://user-images.githubusercontent.com/90144967/226432775-06d2f8a2-e0c9-44ac-a78d-40500e0f3dd1.png)
![after](https://user-images.githubusercontent.com/90144967/226432795-8a016027-cdaf-4104-9bc8-ed859d5c1de9.png)

**Comment by cleuton4k** [comment]
in version 3.0.36 the clipboard is showing strange behavior. when I click on the bottom part of the screen, the clipboard is sometimes in the middle of the screen and sometimes it is below the taskbar. (when I am using the app to record the PC screen, the clipboard is above the taskbar )

https://user-images.githubusercontent.com/90144967/226620647-6fbadf4a-79a8-4790-b764-37d8a1ad4e91.mp4

![02](https://user-images.githubusercontent.com/90144967/226620660-aa79490c-f532-47c5-9f31-d97e8ec1e75b.jpg)
![01](https://user-images.githubusercontent.com/90144967/226620672-a0f987af-a587-4329-a81d-96c4de64845b.png)

**Comment by cleuton4k** [comment]
in version 3.0.37 the clipboard is much better, however I would like you to make a small correction, so that the clipboard is not on top of the menu (insertion extensions) when I click on the bottom part of the screen.

https://user-images.githubusercontent.com/90144967/227403098-35ccf882-519d-4c4a-b734-de7f7ad69274.mp4
