### ISSUE TITLE
backup file does not save certain settings.(bug)

### ISSUE THREAD

**Issue by cleuton4k** [poochie89/SnipDo-Extensions#38]
1. I changed all colors in custom theme to red, saved a backup file and reinstalled snipdo and used the backup file, however the border color was not saved.
2.snipdo does not save extension shortcuts. you could have the app save the shortcuts in the backup file.
![153](https://user-images.githubusercontent.com/90144967/213545126-8eccc808-5dfa-4468-b5f5-dff2133a35d3.png)
![154](https://user-images.githubusercontent.com/90144967/213545131-22bb481a-7e89-4654-a221-ee9746cb2bb5.png)

**Comment by cleuton4k** [comment]
V 3.0.36
![SharedScreenshot](https://user-images.githubusercontent.com/90144967/226383406-4392126b-fe16-4c38-aa84-fa6417bb4f49.jpg)

**Comment by poochie89** [comment]
Can  you send me the backup file?
