### ISSUE TITLE
snipdo does not save window size.

### ISSUE THREAD

**Issue by cleuton4k** [poochie89/SnipDo-Extensions#39]
you could make the app save the size of the window, because when closing the app or restarting the system, the window returns to its previous size.

https://user-images.githubusercontent.com/90144967/213548881-7b33a306-b229-4c2b-ad6d-73edf85a6c90.mp4

**Comment by poochie89** [comment]
This goes against Windows guidelines, dont think i will add this

**Comment by cleuton4k** [comment]
windows guidelines do not understand?

**Comment by poochie89** [comment]
Its not recommended for applications to restore the windowsstate after it has been closed. 
When a user closes a window he expects to "destroy" it
