### ISSUE TITLE
interface bug

### ISSUE THREAD

**Issue by cleuton4k** [poochie89/SnipDo-Extensions#40]
when adding 3 or more text extensions there is a bug in the interface.
v 3.0.34

https://user-images.githubusercontent.com/90144967/213841270-e029ea5e-6a2e-439e-8897-eaa06fc6fac4.mp4

**Comment by poochie89** [comment]
Is this still happening? Can not reproduce on latest version?

**Comment by cleuton4k** [comment]
this is still happening even in version 3.0.35 and also in w10 and w11.

**Comment by cleuton4k** [comment]
3.0.36 and the problem still persists

**Comment by poochie89** [comment]
Hmm i can not reproduce this so I am shooting in the dark...
