### ISSUE TITLE
Ability to set conditions to show button

### ISSUE THREAD

**Issue by emvaized** [poochie89/SnipDo-Extensions#41]
Is there any way to set a condition when certain button will be shown on panel? For example, if I want to show button only when selected text contains some defined keyword?

**Comment by poochie89** [comment]
Yes, thats possible.
You can define a regex in the extension file
See:

https://github.com/poochie89/SnipDo-Extensions#action-definition

**Comment by emvaized** [comment]
Okay, thanks! And is there a way to define button to show only for input fields?

**Comment by poochie89** [comment]
Nope thats not possible

**Comment by emvaized** [comment]
Okay, got it. Thanks!
