### ISSUE TITLE
add button edit created extensions.

### ISSUE THREAD

**Issue by cleuton4k** [poochie89/SnipDo-Extensions#43]
![192](https://user-images.githubusercontent.com/90144967/227395338-20d7bddf-4403-41cd-ae3d-1a97ab89e406.png)

**Comment by cleuton4k** [comment]
receives the 3.0.44 update, but when clicking on "edit" nothing happens, whether in the extensions already created or new ones.

**Comment by poochie89** [comment]
This was accidently activated for some extension, it is not ready yet for production....

**Comment by cleuton4k** [comment]
Do you have a prediction of when it will launch?
