### ISSUE TITLE
Say Text

### ISSUE THREAD

**Issue by big-bang-social** [poochie89/SnipDo-Extensions#45]
### **Extension: Sey the text out loud**
There is no way **to stop the voice** command once it starts reading a text.

**Comment by neoOpus** [comment]
Microsoft (legacy) default voices are awful, MS is starting to add “natural” voices to the narrator but for the moment it would be better if this uses Edge TTS (via a hack like [Edge-TTS](https://github.com/rany2/edge-tts)) but overall TTS is a quite complex problem to have it properly done with language detection etc.
