### ISSUE TITLE
Currency Convertor extension not working

### ISSUE THREAD

**Issue by emvaized** [poochie89/SnipDo-Extensions#46]
Hi there! 
Everytime I try to convert currencies using the extension, I receive this small popup with red cross indicating that some error occured: 
![illustration](https://user-images.githubusercontent.com/37851576/230397081-2ac05c68-4557-4208-b0ee-17c5bf1986c2.png)

And while we are there, maybe it would be also possible to add UAH currency to the supported list? 
I saw that under the hood this extension uses European Central Bank currency rates, but it's list of supported currencies is very limited. Maybe Exchangerate API would be a better deal? It's free, more reliable, and supports way more currencies: 
https://api.exchangerate.host/latest?base=USD

**Comment by poochie89** [comment]
I just tried it and its working fine for me
Can you enable logging execute the extension and send me the logfile?

**Comment by emvaized** [comment]
[log.txt](https://github.com/poochie89/SnipDo-Extensions/files/11184394/log.txt)

**Comment by poochie89** [comment]
I uploaded a new version of the currency converter (v2) with lots if improvements

**Comment by emvaized** [comment]
@poochie89 Great, many thanks! I'll test it later

**Comment by poochie89** [comment]
Look like chatgpt didnt extract all the currencies 😅
Will have to do it manually and update

**Comment by emvaized** [comment]
@poochie89 
Thanks, it seems to be working great now! And also with new supported currencies, thanks a lot 👍

My only issue remaining with this extension is that the buttons appears sometimes, when selected text has nothing similar to currencies. For example, here is some selected text on this page's issue list: 
![illustration](https://user-images.githubusercontent.com/37851576/236991269-62e5b70c-996a-4e65-890f-f3486ae4521d.png) 

Selected text has no numbers and currencies, but popup still shows an option to convert currency. I'm not sure, perhaps it's worth a different issue ticket to be opened? 

Thanks again for your work

**Comment by poochie89** [comment]
The extension has a regex filter when the selected text contains a number.
In some cases though and apps, SnipDo can not recognize the text immediatly, it then shows all the extensions of course. When the user clicks an action, SnipDo then tries to fetch the text using the Windows Clipboard. Previously SnipDo always immediatly fetched the text using the clipboard but thats to much interference with the OS.

Extension is now updated btw. its recommended to restart SnipDo, delete the old extension and then install the new version

**Comment by emvaized** [comment]
@poochie89 
Okay, I see. Too bad it could not read actual text selection sometimes. 
Then I don't have any other issues with Currency extension, and consider this issue completed. Many thanks again!
