### ISSUE TITLE
Where to find the extension list and download?

### ISSUE THREAD

**Issue by katastrophe92** [poochie89/SnipDo-Extensions#47]
Hello there! Where can I find the SnipDo extensions? Is SnipDo also Open Source and you are the developer of the SnipDo? Hope someone can help. Thanks!

**Comment by poochie89** [comment]
Hey i am the developer.
SnipDo itself is not Open Source, only the extensions.
You can find the full list of extensions here:
https://snipdo-app.com/extensions

**Comment by katastrophe92** [comment]
Idk if is fair to add others made extensions to SnipDo. It is a subscription software and not Open Source. You betrayed us customers once. Selling a lifetime app, then converting it to a subscription based. It is not even avaible to download anymore the ex SnipDo

**Comment by poochie89** [comment]
Hey, what do you mean? Almost all extensions are made by myself. And the ones from others devs are added with their permission.
I apologized to the Pantherbar Pro users and gave them up to 5 years SnipDo for free. People dont understand how many hours i have put into this project and how little the software costs. There is a reason this is the only kind of project with this feature, it is quite challenging to implement on Windows. I am doing this project all by myself so i dont think the pricing is unfair
