### ISSUE TITLE
after update 3.0.44, the toolbar does not show all extensions.

### ISSUE THREAD

**Issue by cleuton4k** [poochie89/SnipDo-Extensions#49]
w10 64bit.

https://github.com/poochie89/SnipDo-Extensions/assets/90144967/30f96f93-3c5d-4c9d-891f-f3d0a1c1269f

**Comment by cleuton4k** [comment]
[log.txt](https://github.com/poochie89/SnipDo-Extensions/files/11693251/log.txt)

**Comment by poochie89** [comment]
Does this happen every time?

**Comment by Pylogmon** [comment]
> Just uploaded 3.0.45
> Let me know if its fixed, otherwise please send me an email so we can take a deeper look at it.

This issue still exists in 3.0.45

**Comment by cleuton4k** [comment]
This issue still exists in 3.0.45

**Comment by cleuton4k** [comment]
ok for me✔
