### ISSUE TITLE
ChatGPT extension

### ISSUE THREAD

**Issue by atmomomo** [poochie89/SnipDo-Extensions#50]
ChatGPT extension is fantastic!
But can you support custom URL for API calling? Thanks.

**Comment by poochie89** [comment]
What do you mean with custom URL for the API?

**Comment by atmomomo** [comment]
It's for users who have no direct access to ChatGPT. Please refer to:
[https://github.com/noobnooc/noobnooc/discussions/9](https://github.com/noobnooc/noobnooc/discussions/9)
BTW, would it be possible to support Azure OpenAI call? Such as: [https://github.com/openai-translator/openai-translator#configure-azure-openai-service](https://github.com/openai-translator/openai-translator#configure-azure-openai-service)
Many thanks.

**Comment by poochie89** [comment]
I am currently working on improving the features,
not sure yet if i will add further support beyond what i have, given that the apps focus in not soley on chatgpt
