### ISSUE TITLE
[Bug] On Windows 11, popup has unwanted black border on right and bottom

### ISSUE THREAD

**Issue by emvaized** [poochie89/SnipDo-Extensions#52]
After one of the recent updates, popup appearance got little bit messed up on Windows 11. Popup got black lines on bottom and right sides, and also padding around buttons slightly increased: 
![2023-06-21_22-40](https://github.com/poochie89/SnipDo-Extensions/assets/37851576/90345ddd-6f54-4576-946a-5f50d3be27c7)

**Comment by poochie89** [comment]
Does this still happen in 3.0.49? I think it should be fixed there..

**Comment by emvaized** [comment]
Unfortunately, it still persists in 3.0.49: 
![illustration](https://github.com/poochie89/SnipDo-Extensions/assets/37851576/e8eff84d-6264-4f8e-b305-2827e6510a18)

However, if toolbar appearance set to Horizontal Standard, only black line on bottom remains now: 
![second illustration](https://github.com/poochie89/SnipDo-Extensions/assets/37851576/e8dc0ab6-f706-4574-bdfb-0335a7849576)

**Comment by poochie89** [comment]
Ok man, i tried to get rid of transparent windows because its unstable in Windows,
Dont know if i should switch back to transparency or allow an option to use it (which would def get rid of this issue but would be a bit buggy for some users)

**Comment by emvaized** [comment]
I think having an option would be fine... I don't remember having any issues with stability in my case when tooltip behaved the old way

**Comment by emvaized** [comment]
It seems the problem is solved in v3.0.50.0! Thanks! 
![](https://github.com/poochie89/SnipDo-Extensions/assets/37851576/c5c7abbc-109b-4c4f-9f17-e2121581e7fa)
