### ISSUE TITLE
Search on Google will automatically activate Windows Subsystem for Android

### ISSUE THREAD

**Issue by babaolanqiu** [poochie89/SnipDo-Extensions#53]
I think this happens after latest update. Clicking "Search on google" will automatically start Windows Subsystem for Android, instead of opening a webpage. However, once the system is running, this function works properly again.

**Comment by poochie89** [comment]
Nothing has been changed on my part.
All SnipDo does is calling powershell with the Start-Process command, not much i can do there, i think it is more likely a windows update causing this.

**Comment by babaolanqiu** [comment]
It seems to be a WSA issue microsoft/WSA#342
