### ISSUE TITLE
Get favicon automatically 

### ISSUE THREAD

**Issue by cleuton4k** [poochie89/SnipDo-Extensions#55]
I would like the snipdo to get the icon (favicon) automatically, just like the browsers 
![248](https://github.com/poochie89/SnipDo-Extensions/assets/90144967/973aa054-5a6e-45b4-a694-d4124d45887c)
![Mm](https://github.com/poochie89/SnipDo-Extensions/assets/90144967/1867d2ff-4cf6-48bc-ba59-cd17973fc528)

**Comment by poochie89** [comment]
Cool idea,
will add that
