### ISSUE TITLE
add option to not show extension name.

### ISSUE THREAD

**Issue by cleuton4k** [poochie89/SnipDo-Extensions#56]
![259](https://github.com/poochie89/SnipDo-Extensions/assets/90144967/44502310-4c24-4372-a2f5-143da5fdb651)

**Comment by cleuton4k** [comment]
The tooltips are still shown.
![301](https://github.com/poochie89/SnipDo-Extensions/assets/90144967/a967193b-c490-4069-97f0-ab934bd63509)

**Comment by poochie89** [comment]
The settings only affects extension buttons

**Comment by cleuton4k** [comment]
could you make it not shown?
