### ISSUE TITLE
colored icons

### ISSUE THREAD

**Issue by cleuton4k** [poochie89/SnipDo-Extensions#58]
add a color or black/white icons option to extensions.
![000](https://github.com/poochie89/SnipDo-Extensions/assets/90144967/93152ecd-c3ef-495c-a6e9-fde2c5e7d974)
![267](https://github.com/poochie89/SnipDo-Extensions/assets/90144967/c014838a-884a-4038-879d-5665c2ce3864)

**Comment by poochie89** [comment]
You can already do this when switching monochrome toggle and selecting an image/favicon

**Comment by cleuton4k** [comment]
I'm talking about the icons of the store's extensions and those that already come by default (like copy, paste ...), which by default come in black/white. so it would be nice to be able to choose between colored or black/white icons (as it currently is). because I like the colored icons better. did you understand?

**Comment by poochie89** [comment]
Ok i git it,
will have to think about the best way to add this option….
But would be nice i agree

**Comment by cleuton4k** [comment]
I also think that the icons should come by default colored, but of course putting the option of choice for those who don't like the colored icons.

**Comment by cleuton4k** [comment]
Some icons remain monochrome even after reinstalling the extension.
![280](https://github.com/poochie89/SnipDo-Extensions/assets/90144967/14f31fd5-23b9-4525-8343-51cd17e34a38)

**Comment by poochie89** [comment]
Not all extensions are updated yet
