### ISSUE TITLE
whitespace is being replaced with +

### ISSUE THREAD

**Issue by cleuton4k** [poochie89/SnipDo-Extensions#61]
Whitespace is being replaced with + , even though it is disabled in the settings.
![283](https://github.com/poochie89/SnipDo-Extensions/assets/90144967/25c9df09-d808-431f-bf3c-49d855fea822)
![284](https://github.com/poochie89/SnipDo-Extensions/assets/90144967/4187ff4a-4850-4a27-832c-92d53df106eb)

**Comment by poochie89** [comment]
this is expected behaviour, whitespaces are replaced with "+" for url encoded strings

**Comment by poochie89** [comment]
this seems to be a missunderstanding, it is working as expected,
when toggled whitespaces are replaced with %20, otherwise with +
I will make this clearer in the settings
