### ISSUE TITLE
Snipdo hangs when enabling/disabling transparency.

### ISSUE THREAD

**Issue by cleuton4k** [poochie89/SnipDo-Extensions#65]
Snipdo hangs for approximately 10 seconds and CPU usage increases.

https://github.com/poochie89/SnipDo-Extensions/assets/90144967/e89ac6af-34c9-451a-9fd1-1080d16a68d7

**Comment by poochie89** [comment]
Yeah Windows does a lot of stuff when changing the theme. Not much i can do there
