### ISSUE TITLE
Logged out from pro account and unable to restore purchase

### ISSUE THREAD

**Issue by wildenrou** [poochie89/SnipDo-Extensions#69]
Hi! I'm subscribed to a pro account but every time I restart or update the app I am logged out and limited to a free account, and I am unable to restore my purchase (pro account). 

Attached are a screenshot of the error message I receive when I try to restore my pro account as well as the log file. Many thanks.

![image](https://github.com/poochie89/SnipDo-Extensions/assets/96131182/d0b00832-07e1-4a5b-804b-ca23f3c1e2bf)
[log.txt](https://github.com/poochie89/SnipDo-Extensions/files/12255166/log.txt)

**Comment by poochie89** [comment]
Are you ticking the remember me checkbox when logging in with your account?
________________________________
Von: wildenrou ***@***.***>
Gesendet: Thursday, August 3, 2023 11:25:18 PM
An: poochie89/SnipDo-Extensions ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [poochie89/SnipDo-Extensions] Logged out from pro account and unable to restore purchase (Issue #69)


Hi! I'm subscribed to a pro account but every time I restart or update the app I am logged out and limited to a free account, and I am unable to restore my purchase (pro account).

Attached are a screenshot of the error message I receive when I try to restore my pro account as well as the log file. Many thanks.

[image]<https://user-images.githubusercontent.com/96131182/258240633-d0b00832-07e1-4a5b-804b-ca23f3c1e2bf.png>
log.txt<https://github.com/poochie89/SnipDo-Extensions/files/12255166/log.txt>

**Comment by poochie89** [comment]
Paypal is buggy unfortunately and i will probably remove support for it in the future.
So i recomment changin to a Windows Store subscription

**Comment by wildenrou** [comment]
I initially changed to Paypal, thinking that it would solve the issue I was already experiencing with W store. Thank you for the prompt response. Otherwise, the app is superb.

**Comment by neoOpus** [comment]
> Paypal is buggy unfortunately and i will probably remove support for it in the future. So i recommend changin to a Windows Store subscription


Poochie89,
I wasn't able to do the purchase with Windows Store even if I have points (but unable to verify the account as it doesn't accept my phone number) and tried to make the payment via Debit Card… so I am stuck with the free version forever and the atrocious light theme.

**Comment by poochie89** [comment]
I will try to offer alternative payment methods in the future

**Comment by neoOpus** [comment]
> I will try to offer alternative payment methods in the future

If I can send you MS Points that you can easily convert to $ as payment, that would be great.

**Comment by wildenrou** [comment]
i notice changes since the last update on the account section, hopefully it will fix this, thanks for the quick reaction!

**Comment by neoOpus** [comment]
> i notice changes since the last update on the account section, hopefully it will fix this, thanks for the quick reaction!

Try to log in again and mostly it will re-establish the account. (if you can do a backup before then go for it)
