### ISSUE TITLE
Issue with Text extensions shortcut

### ISSUE THREAD

**Issue by rp1231** [poochie89/SnipDo-Extensions#7]
The text extension pops up even if Ctrl+Alt+a or Ctrl+Alt+c or Ctrl+Alt+x is pressed.
![SnipDo_oHe9pyR0Sv](https://user-images.githubusercontent.com/47380919/186432563-876d720a-063e-4965-b3ce-4c1cc32686e8.png)

It should only pop up if Ctrl+a is pressed etc.

**Comment by poochie89** [comment]
Thanks for the submission, can reproduce this, will be fixed in next update

**Comment by poochie89** [comment]
Are you on 3.19? Should be fixed there. If not let me know which exact combo does still trigger falsely

**Comment by poochie89** [comment]
The fix is available on 3.19.
Wait until you receive the update

**Comment by poochie89** [comment]
Very strange, both of these things dont happen for me on 3.19
I will have to send you a version with some advanced logging to figure out whats happening here.
I will send you a link here....

**Comment by poochie89** [comment]
Is it possible that there is any other application interfering with keyboard events?
SnipDo is really unintrusive now with keyboard interference.

Please install the version below (unpack, rightclick install.ps1, select run with powershell).
Press any of the false combos and send me the logfile

https://www.dropbox.com/s/k8cn5j4gyhous76/SnipDoConverted_3.0.20.0_Test.zip?dl=0

**Comment by poochie89** [comment]
Yes can reproduce, fix is coming
