### ISSUE TITLE
无法升级

### ISSUE THREAD

**Issue by zzrzzr0123** [poochie89/SnipDo-Extensions#71]
你好，无法进行升级到Pro，请问是什么原因
![image](https://github.com/poochie89/SnipDo-Extensions/assets/130990085/c811ef5a-ed6f-4cb8-9171-aef2d15ee6e0)

**Comment by zzrzzr0123** [comment]
![image](https://github.com/poochie89/SnipDo-Extensions/assets/130990085/78c6997c-96b3-465f-bf71-062d5f0073aa)
y以及无法进行安装包安装

**Comment by poochie89** [comment]
This is a windows bug.
Is your account name "Administrator", 
i had reports where this happens when you use the default built in administrator account.

**Comment by zzrzzr0123** [comment]
> This is a windows bug. Is your account name "Administrator", i had reports where this happens when you use the default built in administrator account.

这个账户名是指登录Microsoft Store的账号么？

**Comment by zzrzzr0123** [comment]
这里面支持中国的支付宝么支付么？

**Comment by zzrzzr0123** [comment]
> > 
> 
> No, it refers to your windows user account Alipay is not supported

但是我没法修改我的Window用户的啊~

**Comment by poochie89** [comment]
As i said this is a windows bug and is the only solution i found.
You can google for other possible solutions

**Comment by zzrzzr0123** [comment]
为什么不能单独设置一个付款的方式，还有连接Microsoft Store【这个是真的很难用啊~】

**Comment by poochie89** [comment]
The sdks for subscription on the .net platform are all terrible, if there is one you are aware of let me know

**Comment by zzrzzr0123** [comment]
> The sdks for subscription on the .net platform are all terrible, if there is one you are aware of let me know

1. **RabbitMQ**
2. **MassTransit**
3. **Azure Service Bus**
4. **Kafka**
5. **NATS**

也许你可以试试看，但是我对不能使用付费Pro的功能表示感到很遗憾！

**Comment by poochie89** [comment]
These are not billing services, but thanks, i will think about adding other payment services in the future
