### ISSUE TITLE
UI tweaks suggestions

### ISSUE THREAD

**Issue by neoOpus** [poochie89/SnipDo-Extensions#73]
Hi,

I would like to contribute to this project by helping with the icons and also suggesting some UI tweaks to make everything neat and customizable to everyone's liking, I love how this has progressed since PantherBar.

![image](https://github.com/poochie89/SnipDo-Extensions/assets/1388336/7ae4395f-2a81-44ac-8cbe-a5c42a3df785)

I propose making it possible to change the icons, alter the color of Monotone, like you did for folders. Moreover, please allow “edit” folders in them using the right-click menu.

![image](https://github.com/poochie89/SnipDo-Extensions/assets/1388336/947a47b6-d4ea-4c3d-87f1-772312cf4057)

fix the size of these for example
![image](https://github.com/poochie89/SnipDo-Extensions/assets/1388336/31b33e93-350e-4bbe-ae8a-736b317dab59)

**Comment by poochie89** [comment]
> Hi,
> 
> I would like to contribute to this project by helping with the icons and also suggesting some UI tweaks to make everything neat and customizable to everyone's liking, I love how this has progressed since PantherBar.
> 
> ![image](https://user-images.githubusercontent.com/1388336/260234101-7ae4395f-2a81-44ac-8cbe-a5c42a3df785.png)
> 

The monochrome foreground color can be changed by using a custom bar theme and setting the foreground color. Editing extension and folders (including icon) is on the feature request list and will be implemented at some point.


> I propose making it possible to change the icons, alter the color of Monotone, like you did for folders. Moreover, please allow “edit” folders in them using the right-click menu.
> 
> ![image](https://user-images.githubusercontent.com/1388336/260233042-947a47b6-d4ea-4c3d-87f1-772312cf4057.png)
> 
> fix the size of these for example ![image](https://user-images.githubusercontent.com/1388336/260234040-31b33e93-350e-4bbe-ae8a-736b317dab59.png)

Why do you to fix the size of this? New users will not be able to tell what this menus mean?

**Comment by neoOpus** [comment]
> Why do you fix the size of this? New users will not be able to tell what these menus mean?

I mean, the icons are squished and making them a little bigger and have the proper aspect-ratio (and every other icon uniform in size and style) would be a good idea.

For the extensions icons, it would be better to have all of them in SVG, so they stay crisp and, of course, all of them have the same style just like icon packs in smartphones.

`Copy / Cut / Paste / Share` if they adopt the Windows 11 style it is much better than just some random style (and everything else too to improve consistency) by adopting the same language (dimension, spacing, effects, animations, icons, and font). So it looks and works just like a native Windows 11 menu.


![image](https://github.com/poochie89/SnipDo-Extensions/assets/1388336/cf1d5ea4-5b10-45ff-a7a6-0b346bc8a1e5)

**Comment by poochie89** [comment]
I will add svg support in the next release,
i tried using the standard windows context menu icons, but they did not fit well with other icons. 
The picture you posted shows what i mean, this doesnt seem that consistent to me (colored winrar icon + simplistic windows icons)
I will also try to make the Settings icons more uniform

**Comment by neoOpus** [comment]
> I will add svg support in the next release, i tried using the standard windows context menu icons, but they did not fit well with other icons. The picture you posted shows what i mean, this doesnt seem that consistent to me (colored winrar icon + simplistic windows icons) I will also try to make the Settings icons more uniform

let me know if I can help with that

**Comment by neoOpus** [comment]
I find this icon set broader, more representative and overall nicer 

https://fonts.google.com/icons

**Comment by poochie89** [comment]
It looks like there are no colored version of this iconset?

**Comment by neoOpus** [comment]
They are available in [two tones](https://marella.me/material-icons/demo/#two-tone)

I am thinking seriously about finding some time and motivation to make an icon set for you that has a consistent style and that is colorful but not too colorful.

**Comment by poochie89** [comment]
The two tones look terrible to me 😅
That would be cool, i tried a slightly different icon set on the new version let me know what you think

**Comment by neoOpus** [comment]
I like them a bit more, but they are too colorful and not uniform.

 I am the kind of person who wants everything to be pixel-perfect, and I notice when icons aren't from the same family, not the same quality, not dimensionally right. Sort of UI-OCD 😆

**Comment by neoOpus** [comment]
> I can understand that 😊 Maybe you find a cool colored icon set I will check the material one out again and may use it for the monochrome colors

If you make every icon in the UI modifiable, then I will take care of picking them one-by-one and share with you the result and probably also creating a full set, for the moment, I found in the backup that I could alter the images (didn't test it yet) so I will play with that… but definitely being able to modify the icons and title at any moment from UI is much better.

**Comment by poochie89** [comment]
Yes editing the extension will be in the next bigger release

**Comment by neoOpus** [comment]
I have another tiny suggestion, which is to make a placeholder in the main toolbar for the last used extension (tool). This way it is easier to find it, it could be placed by the end-user wherever they like.

Furthermore, please make the folders show next to the main toolbar instead of being over it sometimes and some other on top or bottom but very far. (search folder in my example from the backup), if you are not planning, of course, to make this even better with some different design.

**Comment by poochie89** [comment]
> I have another tiny suggestion, which is to make a placeholder in the main toolbar for the last used extension (tool). This way it is easier to find it, it could be placed by the end-user wherever they like.

Thats an interesting idea, i may add that at some point

> 
> Furthermore, please make the folders show next to the main toolbar instead of being over it sometimes and some other on top or bottom but very far. (search folder in my example from the backup), if you are not planning, of course, to make this even better with some different design.

Sorry I couldnt understand what you mean here

**Comment by neoOpus** [comment]
Here is a screenshot

![image](https://github.com/poochie89/SnipDo-Extensions/assets/1388336/98fed46f-d218-41f6-baf7-9fd0b068f722)

As you can see, the search folder toolbar appears far away from the main toolbar. Also, the tooltip sometimes hides the icons beneath it. 

![image](https://github.com/poochie89/SnipDo-Extensions/assets/1388336/71bc6c87-c5de-4659-a0eb-32518ab17b8a)

Please consider this as low priority!

**Comment by neoOpus** [comment]
A preview of Mica effect appled to SnipDo

![image](https://github.com/poochie89/SnipDo-Extensions/assets/1388336/7f43bd3b-fa28-4a7a-b358-b4580b6c106f)

**Comment by poochie89** [comment]
I think showing the folder contents right below the folder extension is the only behaviour that makes sense.
Mica effects is aleary applied

**Comment by neoOpus** [comment]
Please make this project open source!
