### ISSUE TITLE
Unable to use the same icons for monochrome and colored

### ISSUE THREAD

**Issue by neoOpus** [poochie89/SnipDo-Extensions#77]
The same icon shows up as monochrome and colored, but when I click the create button, it throws an error or just stays stuck.

The colored icon is currently converted to monochrome (B&W) and that seems to be working well.

**Comment by neoOpus** [comment]
Sure let me detail that also report another that is related

1. Click Create Folder (in Text Extensions)
2. Give it a name
3. Click to add a monochrome icon (Icon)
4. Pick your icon (PNG), / it is a colored icon but shows as B&W (nice feature to have it desaturated automatically)
5. Click to add a colored icon (Icon colored)
6. Click the Create button, nothing happens (or shows an error)

![image](https://github.com/poochie89/SnipDo-Extensions/assets/1388336/369da2f9-beb2-4952-8a01-284d52b141cd)



Another issue is the conversion of an SVG to monochrome shows as a black box (then as white once added)

![image](https://github.com/poochie89/SnipDo-Extensions/assets/1388336/f445cec5-2630-4028-88cb-3570a7ff7fe4)

**Comment by poochie89** [comment]
Oh think i forgot to add this fix to folders,
Will be fixed on next update
