### ISSUE TITLE
Some of the config is lost after update

### ISSUE THREAD

**Issue by neoOpus** [poochie89/SnipDo-Extensions#78]
I configured a folder before the update that contains Dev tools, and now I was looking and tweaking and found that it is missing as well as some other separate icons (QTranslate), there are some other issues with the account, but I fixed them via logging-out and redoing the purchase process…

I am reporting these issues to help you make this as robust as it should be ;)

Now I am going to re-add the plugins and re-organizing them and I will be back maybe with some other bug reports

**Comment by poochie89** [comment]
This could have been a side effect of the new subscription system. You may have been reverted to free version and it removed the folders/extensions. I dont think it will happen again. Let me know otherwise
