### ISSUE TITLE
[Suggestions] to improve UI/UX

### ISSUE THREAD

**Issue by neoOpus** [poochie89/SnipDo-Extensions#79]
I wanted to re-organize things into folders and re-assign some meaningful text and icons, but once the folder is created it is not possible to rename it or change its icon. As moving them around isn't easy either, you have to drop it over the folder name; otherwise it wouldn't be inserted into it, instead of being able to just drop it anywhere inside the tree boundaries. As well as being able to edit all the elements (folders, extensions) text and icons.

1. Folders boundaries need to have a distinctive color or background to spot them easily
 
2. Another thing that would be nice is to see a tooltip with the description of each extension, predefined categories in the store "Load extensions".

3. Extensions need to have a sorting that would sort them by name or tags (having tags would make it easier to find and add them, example : `Search`, `Translate`, `Note`) and a consistent naming scheme like (if tags aren't a possible to have)
          - (Search Twitter / Search Yandex / Search Google / Search Google Scholars / Search Google Image)
          - (Add to Todoist / Add to Sticky Note)
          - (Convert Currency / Convert Unit / Convert HexDec / Convert Color / Convert Base64)
          - (Translate with QTranslate / Translate with Reverso / Translate with Google / Translate with Bing)

4. Nested folders

5. Adding new extensions should move them to the bottom by default, and the same for those removed from a folder should just end on the top or bottom of it instead on the top most.

So, it would be very much appreciate if this can be improved in the future.

**Comment by neoOpus** [comment]
I forgot to mention that I truly appreciate the immense effort you have invested in this project. I understand the complexity and multitude of details that need to be considered. As a power user who prefers mouse buttons over the keyboard, I find this software extremely useful and it has truly revolutionized my experience.

Furthermore, I want to mention that I am attempting to envision a future where extensions become more abundant and potentially easier for anyone to create through the same GUI. This future may involve having pre-designed templates available for searching, making it as simple as inserting the URL and changing the image. Additionally, there could be a seamless process of transforming selected text by connecting various pre-existing and extensive function nodes in a single pass.

Having preparations in place for such a scenario is a wise decision in my opinion. Personally, I intend to complete the tasks I am currently working on with my computer, which mostly involve configuration of a development environment. Afterward, I will proceed to create some extensions.

**Comment by poochie89** [comment]
> I wanted to re-organize things into folders and re-assign some meaningful text and icons, but once the folder is created it is not possible to rename it or change its icon. As moving them around isn't easy either, you have to drop it over the folder name; otherwise it wouldn't be inserted into it, instead of being able to just drop it anywhere inside the tree boundaries. As well as being able to edit all the elements (folders, extensions) text and icons.
> 
> 1. Folders boundaries need to have a distinctive color or background to spot them easily
How do you envision this? Could you make a quick sketch?

> 2. Another thing that would be nice is to see a tooltip with the description of each extension, predefined categories in the store "Load extensions".
> 3. Extensions need to have a sorting that would sort them by name or tags (having tags would make it easier to find and add them, example : `Search`, `Translate`, `Note`) and a consistent naming scheme like (if tags aren't a possible to have)
>    - (Search Twitter / Search Yandex / Search Google / Search Google Scholars / Search Google Image)
>    - (Add to Todoist / Add to Sticky Note)
>    - (Convert Currency / Convert Unit / Convert HexDec / Convert Color / Convert Base64)
>    - (Translate with QTranslate / Translate with Reverso / Translate with Google / Translate with Bing)

Thats a good idea, i might add tags to the store

> 4. Nested folders
I am not a fan of this

> 5. Adding new extensions should move them to the bottom by default, and the same for those removed from a folder should just end on the top or bottom of it instead on the top most.
Ok

> 
> So, it would be very much appreciate if this can be improved in the future.

**Comment by neoOpus** [comment]
Here is a quick way preview (with highlight) but consider it to be a background color that is a slightly different and maybe a share of yellow that goes well with a dark theme and a lighter one for like theme…
![image](https://github.com/poochie89/SnipDo-Extensions/assets/1388336/8cd52f97-745c-424e-8e9e-c16ac28f68c8)

 Or might be just a yellow outline if you find it better.
![image](https://github.com/poochie89/SnipDo-Extensions/assets/1388336/a8ba93d0-3d98-41bb-92cc-663257fcb657)
