### ISSUE TITLE
Quantum Superposition :P

### ISSUE THREAD

**Issue by neoOpus** [poochie89/SnipDo-Extensions#80]
I encountered this bug while adding extensions to a folder

![image](https://github.com/poochie89/SnipDo-Extensions/assets/1388336/14edf957-36ad-4abf-a07a-4a539b9de367)

**Comment by poochie89** [comment]
Hmm how can i reproduce this?
Did this happen after a certain amount of added extensions?

**Comment by emvaized** [comment]
@poochie89 
I got my Search button replaced with Google one after recent update. Is it possible to get back the previous Search button, with magnifier glass icon?

**Comment by neoOpus** [comment]
> Hmm how can i reproduce this? Did this happen after a certain amount of added extensions?

Yes I tried to add many extensions and put them into folders, if you want I can send you my backup file

**Comment by poochie89** [comment]
A backupfile would be very helpful. You can also include the notepad++ icon that only shows in monochrome colors.

**Comment by neoOpus** [comment]
Here it is, it is a WIP for what could fit best to my needs, the Notepad++ extension is included (the created extensions don't create a sub-folder like other when I checked this as a zip file)

[settings#7.zip](https://github.com/poochie89/SnipDo-Extensions/files/12500500/settings.7.zip)
