### ISSUE TITLE
Icon is monochrome by default

### ISSUE THREAD

**Issue by neoOpus** [poochie89/SnipDo-Extensions#81]
When I create an extension and add two icons (monochrome, colored) then after the extension is created, even if the selected toolbar appearance is colored it still opts to use the monochrome icon, instead of having both option available and switching between them dynamically according to the selected appearance.

![image](https://github.com/poochie89/SnipDo-Extensions/assets/1388336/98b7558e-7401-4fc3-9084-db211bac68f3)

**Comment by poochie89** [comment]
I can not reprodice this, its working as expected for me.
can you explain step by step?

**Comment by neoOpus** [comment]
> I can not reprodice this, its working as expected for me. can you explain step by step?

Sure!

I try to create an extension
![image](https://github.com/poochie89/SnipDo-Extensions/assets/1388336/d8250ee5-b7b0-4513-b0a5-e0bb41714d32)

Then once I click over the Create button
![image](https://github.com/poochie89/SnipDo-Extensions/assets/1388336/01744086-df32-4487-ae05-30c79696aea9)

The icon should be preferably colored since the appearance is set to Colored
![image](https://github.com/poochie89/SnipDo-Extensions/assets/1388336/21c4c98a-d16c-4078-b4cb-0ba9cf49942f)

And switch to monochrome if we change the appearance to monochrome

**Comment by poochie89** [comment]
Hmm very strange, it works totally fine for me, does this happen with every kind of extension you create?

**Comment by poochie89** [comment]
Found this bug,
will be released in the next version.
You will have to recreate the extension  though

**Comment by neoOpus** [comment]
> Found this bug, will be released in the next version. You will have to recreate the extension though

Sounds great and yeah no worries about the extension
