### ISSUE TITLE
New action icons get cropped on right side with Size less than default

### ISSUE THREAD

**Issue by emvaized** [poochie89/SnipDo-Extensions#86]
Most recent update (3.0.61.0) introduced a bunch of new icons for actions, such as "Copy" and new search icon ("Google" logo in my case). However, when size of tooltip is set to less than default value, icons get cropped on the right side: 
![illustration monochrome icons](https://github.com/poochie89/SnipDo-Extensions/assets/37851576/be68e952-7c59-4e47-b94e-c0b6afbb6d59)

Colorful icons also seem to be affected by this, but slightly less (only visible on Google logo): 
![illustration coloful icons](https://github.com/poochie89/SnipDo-Extensions/assets/37851576/96d877eb-27da-4ed0-bd39-50127bcd9251)

Important to note — my monitor resolustion is 2560x1440, and UI scaling is 125%

**Comment by poochie89** [comment]
thanks, look like scaling affects new vector icons, will fix

**Comment by emvaized** [comment]
Problem is fixed now in version 3.0.62.0
Thanks!
