### ISSUE TITLE
QTranslate Custom Shortcut

### ISSUE THREAD

**Issue by neoOpus** [poochie89/SnipDo-Extensions#87]
In MS Edge, the default QTranslate Hotkey `Ctrl+Q` opens the [Command Palette](https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/experimental-features/edge-command-palette#open-command-palette)

So please make it possible to change that! (if this easy to implant) otherwise keep your actual priorities and I will re-create that extension.

**Comment by neoOpus** [comment]
I am unable to set the shortcut for `CTRL+`\` when I try that it changes it to `CTRL+C`

**Comment by neoOpus** [comment]
I hope you are working on resolving this issue. I believe the MS PowerToys project effectively manages the creation of Hotkeys, and since it is open source, you may want to examine its functionality.

**Comment by poochie89** [comment]
I can not reproduces this, what do you mean with it changes  to Ctrl+C?
It could be that another app is already using a specific shortcut and you need to use another one.

**Comment by neoOpus** [comment]
I think it is still problematic

![image](https://github.com/poochie89/SnipDo-Extensions/assets/1388336/111d7e91-9aae-4ecb-b736-ca8e67d10714)

**Comment by poochie89** [comment]
The ‘ sign and some other are invalid triggerkeys. You need to use another one.
Am 26. Sep. 2023, 19:13 +0200 schrieb Anoir Ben Tanfous ***@***.***>:

**Comment by neoOpus** [comment]
Actually, it is because it is the most convenient for me. That's why I am asking. I tried CTRL+F1 or F2, but I didn't like them because they trigger something else if I don't click them properly with CTRL down.
Thank you anyway :)

**Comment by poochie89** [comment]
You can use other special keys you can use, there are just a few exceptions
Am 26. Sep. 2023, 19:26 +0200 schrieb Anoir Ben Tanfous ***@***.***>:
