### ISSUE TITLE
Installed corner banner

### ISSUE THREAD

**Issue by neoOpus** [poochie89/SnipDo-Extensions#90]
Hello,

Thank you for implementing the filters! :)

I have an interesting suggestion: adding a corner banner for installed extensions, and possibly including a filter to show only the non-installed ones.

something like without any fancy design...
![image](https://github.com/poochie89/SnipDo-Extensions/assets/1388336/1930adc8-be75-4fa6-9636-4a9b0b68a4ee)

Moreover, I would like to report a bug for ClipDo. However, I couldn't find where to do so as the website URL is dead and there is no GitHub section for it. Nevertheless, the bug is related to the Right-to-Left Support feature. Currently, the text is displayed reversed and without proper alignment and each character is isolated.

**Comment by poochie89** [comment]
Good idea 👍 
Can you send me a screenshot of the clipdo bug?

**Comment by neoOpus** [comment]
Sure here it is, actually I found the same text if copied from notepad or github then it shows just fine but when it is copied from Facebook it becomes unreadable.

example:
هذا نص عربي من اليمين إلى اليسار

![image](https://github.com/poochie89/SnipDo-Extensions/assets/1388336/7cb5fdc3-ca56-46bc-a565-2f0a96d35fc5)
I am also trying to track a bug that causes it to crash often.

**Comment by neoOpus** [comment]
Thank you for the update of ClipDo, this has resolved the previous issue, and it is readable now :). What is remaining is to align the text to the right if that's possible. !

![image](https://github.com/poochie89/SnipDo-Extensions/assets/1388336/727452a6-42e4-4201-85bd-93520b771f32)


I also have a few suggestions 

1. [feature] Use a hashing algorithm to prevent duplication of content, reducing clutter and database size. If the content already exists in an organized list, it will be displayed with the appropriate colour, indicating that it is older.
2. [enhancement] Each element has a top-left checkbox that allows for selecting multiple options for deletion, pasting, organization, and more.
3. [bug fix] Avoid scrolling to the start after removing an element.
4. [feature] Add a button to the UI that allows users to easily scroll to the top of the screen. This will prevent any obstruction of important information while looking for what to paste or doing a search.

**Somehow, I am unable to access the premium features in SnipDo today! I am not sure about the cause of this, but I hope to find a solution soon.**

**Comment by neoOpus** [comment]
Hi,

I have another suggestion / request, when a paragraph is copied most of it doesn't show as there is no word-wrap feature implanted.

The right-click menu often fails to work and I have to restart the app, maybe a restart function from the systray to all your apps is needed that will just do that. Instead of closing then looking for it on the start-menu to re-launch.

Also if possible make the main windows when the icon on the systray is clicked or double-clicked to avoid using the hotkey.

**Comment by poochie89** [comment]
> Hi,
> 
> I have another suggestion / request, when a paragraph is copied most of it doesn't show as there is no word-wrap feature implanted.

you mean sometimes some words are cut off?
This only happens when you copy from a browser correct? The html renderer library does this. I may need to use another library


> 
> The right-click menu often fails to work and I have to restart the app, maybe a restart function from the systray to all your apps is needed that will just do that. Instead of closing then looking for it on the start-menu to re-launch.

What happens when rightclicking? Does it freeze?

> 
> Also if possible make the main windows when the icon on the systray is clicked or double-clicked to avoid using the hotkey.

Thats a good idea 👍
