### ISSUE TITLE
Fell back to Free

### ISSUE THREAD

**Issue by neoOpus** [poochie89/SnipDo-Extensions#92]
Hi,

My account for the second time fell back to Free even if I already paid for premium (Paypal)

Transaction ID
8HX02134YU252262K

**Comment by poochie89** [comment]
Can you give me a couple of infos?
When did you sign up last time?
Did the account show "Free User" when checking the "Manage Account" Window?
Is it possible that a firewall is blocking SnipDo?
Did you change any PC parts?
