### ISSUE TITLE
several problems with creating an extension shortcut.

### ISSUE THREAD

**Issue by cleuton4k** [poochie89/SnipDo-Extensions#95]
-does not recognize the ptbr keyboard standard, cannot use the ç (cedilha) key for combinations.
-it is not possible to use the windows key for combinations.
-when using the combinations ctrl+q and ctrl+e, the combination shown is ctrl+c
-the following combinations do not work: alt+q, alt+a, alt+z
![641](https://github.com/poochie89/SnipDo-Extensions/assets/90144967/6466ee89-8013-44d3-9b75-ddf55d62c2d5)
![642](https://github.com/poochie89/SnipDo-Extensions/assets/90144967/938056ba-d344-488e-8b89-ca53fe470721)

**Comment by poochie89** [comment]
These thinkgs are working for me on a german keyboard.
Could you enable logging, try the things you mentioned and send me the file?

**Comment by cleuton4k** [comment]
[log.txt](https://github.com/poochie89/SnipDo-Extensions/files/13843811/log.txt)

**Comment by cleuton4k** [comment]
Alt+Q, Alt+A, Alt+Z conflito com outro programa "windowstop", consegui resolver esse problema.
Ctrl+Q e Ctrl+E conflito com "Qtranslate". porem descobre que para a extensão(Qtranslate)) funcionar precisa usar o atalho ctrl+q para chamar a janela do programa, teria com vc mudar a forma como chamar o Qtranslate sem usar tecla de atalho?
![651](https://github.com/poochie89/SnipDo-Extensions/assets/90144967/ad04dc6a-ec3f-421f-845b-2268da17596b)
