### ISSUE TITLE
paste and go extension conflicts with logi options+

### ISSUE THREAD

**Issue by cleuton4k** [poochie89/SnipDo-Extensions#99]
logi options+ has a function to show a notification every time the capslock, numlock, scroollock and fnlock keys are pressed, but every time the "paste and go" extension is activated, a num lock notification is shown. So I asked chatgpt to create a PowerShell script that performed the same "paste and go" function, but written in a different way to avoid conflict. and with this new code the message is no longer displayed. Could you change to this code?
 
![648](https://github.com/poochie89/SnipDo-Extensions/assets/90144967/cdb35c0e-5f93-468f-aac6-773541ec003f)
![650](https://github.com/poochie89/SnipDo-Extensions/assets/90144967/eceb2fb2-b920-406e-941a-0d97e52cf2b1)

**Comment by cleuton4k** [comment]
[paste and go.txt](https://github.com/poochie89/SnipDo-Extensions/files/13928356/paste.and.go.txt)

**Comment by poochie89** [comment]
great will update the extension
